import '../models/gesture.dart';
import '../models/lesson.dart';

/// Mock data provider for gestures and lessons.
/// Replace with API/database layer in production.
class MockDataService {
  static final List<GestureModel> _gestures = [
    const GestureModel(
      id: 'g1',
      name: 'Hello',
      category: 'Greetings',
      description: '',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0001.mp4',
      instructions: [
        'Raise your dominant hand to ear level',
        'Keep palm open, fingers together',
        'Wave hand side to side 2-3 times',
      ],
      tips: [
        'Keep movements smooth and clear',
        'Maintain eye contact',
        'Smile while signing',
      ],
      estimatedMinutes: 2,
      isLearned: true,
    ),
    const GestureModel(
      id: 'g2',
      name: 'Thank You',
      category: 'Greetings',
      description: 'Express gratitude',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0013.mp4',
      instructions: [
        'Touch your chin with fingertips',
        'Move hand forward and down',
        'Keep palm facing up',
      ],
      tips: [
        'Start with fingers touching chin',
        'Smooth outward motion',
        'Show genuine appreciation in expression',
      ],
      estimatedMinutes: 2,
      isLearned: true,
      isMastered: true,
    ),
    const GestureModel(
      id: 'g3',
      name: 'Please',
      category: 'Greetings',
      description: 'Make a polite request',
      difficulty: 'Medium',
      videoUrl: 'assets/videos/letters/D.mp4',
      instructions: [
        'Place hand flat on chest',
        'Move in circular motion',
        'Keep movement smooth',
      ],
      tips: [
        'Circle clockwise',
        'Maintain gentle pressure',
        'Facial expression is important',
      ],
      estimatedMinutes: 3,
      isLearned: false,
      prerequisite: 'g2',
    ),
    const GestureModel(
      id: 'g4',
      name: 'Good',
      category: 'Greetings',
      description: 'Morning greeting - Good',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0018.mp4',
      instructions: [
        'Sign "good" first',
        'Then sign "morning"',
        'Combine smoothly',
      ],
      tips: [
        'Practice each part separately first',
        'Then combine them',
        'Keep natural rhythm',
      ],
      estimatedMinutes: 3,
      isLearned: false,
    ),
    const GestureModel(
      id: 'g5',
      name: 'Goodbye',
      category: 'Greetings',
      description: 'Farewell gesture',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0027.mp4',
      instructions: [
        'Raise hand with palm facing person',
        'Open and close fingers',
        'Repeat 2-3 times',
      ],
      tips: [
        'Keep motion visible',
        'Smile warmly',
        'Make eye contact',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'f1',
      name: 'Mother',
      category: 'Family',
      description: 'Sign for mother',
      difficulty: 'Easy',
      // Asset file available in this repo: assets/videos/family/0083.mp4
      videoUrl: 'assets/videos/family/0083.mp4',
      instructions: [
        'Touch thumb to chin',
        'Spread fingers',
        'Keep hand relaxed',
      ],
      tips: [
        'Gentle touch',
        'Clear finger position',
        'Calm expression',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'f2',
      name: 'Father',
      category: 'Family',
      description: 'Sign for father',
      difficulty: 'Easy',
      // Asset file available in this repo: assets/videos/family/0083.mp4
      videoUrl: 'assets/videos/family/0083.mp4',
      instructions: [
        'Touch thumb to forehead',
        'Spread fingers',
        'Keep hand relaxed',
      ],
      tips: [
        'Similar to "mother" but at forehead',
        'Clear distinction',
        'Confident posture',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'f3',
      name: 'Sister',
      category: 'Family',
      description: 'Sign for sister',
      difficulty: 'Medium',
      // Asset file available in this repo: assets/videos/family/0083.mp4
      videoUrl: 'assets/videos/family/0083.mp4',
      instructions: [
        'Sign "girl" first',
        'Then sign "same"',
        'Combine smoothly',
      ],
      tips: [
        'Two-part sign',
        'Practice transitions',
        'Keep consistent speed',
      ],
      estimatedMinutes: 3,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n0',
      name: 'Zero',
      category: 'Numbers',
      description: 'Number 0',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/0.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n1',
      name: 'One',
      category: 'Numbers',
      description: 'Number 1',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/1.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n2',
      name: 'Two',
      category: 'Numbers',
      description: 'Number 2',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/2.mp4',
      instructions: [
        'Raise index and middle finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Fingers should be separated',
        'Keep hand steady',
        'Clear V shape',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n3',
      name: 'Three',
      category: 'Numbers',
      description: 'Number 3',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/3.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n4',
      name: 'Four',
      category: 'Numbers',
      description: 'Number 4',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/4.mp4',
      instructions: [
        'Raise index and middle finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Fingers should be separated',
        'Keep hand steady',
        'Clear V shape',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n5',
      name: 'Five',
      category: 'Numbers',
      description: 'Number 5',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/5.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n6',
      name: 'Six',
      category: 'Numbers',
      description: 'Number 6',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/6.mp4',
      instructions: [
        'Raise index and middle finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Fingers should be separated',
        'Keep hand steady',
        'Clear V shape',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n7',
      name: 'Seven',
      category: 'Numbers',
      description: 'Number 7',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/7.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n8',
      name: 'Eight',
      category: 'Numbers',
      description: 'Number 8',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/8.mp4',
      instructions: [
        'Raise index and middle finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Fingers should be separated',
        'Keep hand steady',
        'Clear V shape',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n9',
      name: 'Nine',
      category: 'Numbers',
      description: 'Number 9',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/9.mp4',
      instructions: [
        'Raise index finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Clear finger position',
        'Keep hand steady',
        'Confident posture',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n10',
      name: 'Ten',
      category: 'Numbers',
      description: 'Number 10',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/numbers/10.mp4',
      instructions: [
        'Raise index and middle finger',
        'Keep other fingers closed',
        'Palm facing forward',
      ],
      tips: [
        'Fingers should be separated',
        'Keep hand steady',
        'Clear V shape',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'n54',
      name: 'Fifty Four',
      category: 'Numbers',
      description: 'Number 54',
      difficulty: 'Medium',
      videoUrl: 'assets/videos/numbers/54.mp4',
      instructions: [
        'Sign fifty first',
        'Then sign four',
        'Combine both clearly in sequence',
      ],
      tips: [
        'Keep each number distinct',
        'Use steady hand positioning',
        'Pause briefly between the two signs',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter1',
      name: 'A',
      category: 'Letters',
      description: 'Letter A handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/A.mp4',
      instructions: [
        'Make a closed fist',
        'Rest thumb along the side',
        'Keep knuckles facing forward',
      ],
      tips: [
        'Keep the hand still',
        'Show the thumb clearly',
        'Hold for a moment before switching',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'B',
      category: 'Letters',
      description: 'Letter B handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/B.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'C',
      category: 'Letters',
      description: 'Letter C handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/C.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'D',
      category: 'Letters',
      description: 'Letter D handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/D.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear D shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the D shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'E',
      category: 'Letters',
      description: 'Letter E handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/E.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear E shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the E shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'F',
      category: 'Letters',
      description: 'Letter F handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/F.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'G',
      category: 'Letters',
      description: 'Letter G handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/G.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear G shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the G shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'H',
      category: 'Letters',
      description: 'Letter H handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/H.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'I',
      category: 'Letters',
      description: 'Letter I handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/I.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear I shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the I shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'J',
      category: 'Letters',
      description: 'Letter J handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/J.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'K',
      category: 'Letters',
      description: 'Letter K handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/K.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear K shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the K shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'L',
      category: 'Letters',
      description: 'Letter L handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/L.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'M',
      category: 'Letters',
      description: 'Letter M handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/M.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear M shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the M shape distinct',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'N',
      category: 'Letters',
      description: 'Letter N handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/N.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'O',
      category: 'Letters',
      description: 'Letter O handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/O.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear O shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the O shape round',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'P',
      category: 'Letters',
      description: 'Letter P handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/P.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'Q',
      category: 'Letters',
      description: 'Letter Q handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/Q.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear Q shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the C shape round',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'R',
      category: 'Letters',
      description: 'Letter R handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/B.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'S',
      category: 'Letters',
      description: 'Letter S handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/S.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear S shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the S shape smooth',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'T',
      category: 'Letters',
      description: 'Letter T handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/T.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'U',
      category: 'Letters',
      description: 'Letter U handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/U.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear U shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the U shape round',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'V',
      category: 'Letters',
      description: 'Letter V handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/V.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'W',
      category: 'Letters',
      description: 'Letter W handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/W.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear W shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the W shape round',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'X',
      category: 'Letters',
      description: 'Letter X handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/X.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter3',
      name: 'Y',
      category: 'Letters',
      description: 'Letter Y handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/Y.mp4',
      instructions: [
        'Curve fingers and thumb',
        'Form a clear Y shape',
        'Keep palm facing sideways',
      ],
      tips: [
        'Do not close the hand fully',
        'Keep the Y shape round',
        'Use smooth transitions between letters',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'letter2',
      name: 'Z',
      category: 'Letters',
      description: 'Letter Z handshape',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/letters/Z.mp4',
      instructions: [
        'Raise fingers straight up',
        'Keep fingers together',
        'Fold thumb across the palm',
      ],
      tips: [
        'Keep fingers tight together',
        'Palm should face forward',
        'Avoid bending fingers',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'food1',
      name: 'Food',
      category: 'Food',
      description: 'Sign for food',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/food/0063.mp4',
      instructions: [
        'Bring fingers to mouth',
        'Repeat motion',
        'Natural eating gesture',
      ],
      tips: [
        'Keep movements smooth',
        'Clear hand-to-mouth motion',
        'Comfortable pace',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'f4',
      name: 'Parents',
      category: 'Family',
      description: 'Sign for parents',
      difficulty: 'Medium',
      videoUrl: 'assets/videos/family/0083.mp4',
      instructions: [
        'Combine mother and father signs',
        'Sign for both parents',
        'Smooth transition between signs',
      ],
      tips: [
        'Practice each sign separately first',
        'Keep movements clear',
        'Natural flow',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase1',
      name: 'Users',
      category: 'Common Phrases',
      description: 'Sign for users or people',
      difficulty: 'Medium',
      videoUrl: 'assets/videos/common_phrases/0089.mp4',
      instructions: [
        'Indicate multiple people',
        'Sweeping motion',
        'Include everyone gesture',
      ],
      tips: [
        'Wide sweeping motion',
        'Include all directions',
        'Clear indication of group',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'g6',
      name: 'Morning',
      category: 'Greetings',
      description: 'Time of day - morning',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0019.mp4',
      instructions: [
        'Bring arm up like sunrise',
        'Palm facing up',
        'Smooth upward motion',
      ],
      tips: [
        'Think of the sun rising',
        'Keep movement fluid',
        'End at chest level',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'g7',
      name: 'Afternoon',
      category: 'Greetings',
      description: 'Time of day - afternoon',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0020.mp4',
      instructions: [
        'Arm at an angle',
        'Palm down position',
        'Represents sun at midday',
      ],
      tips: [
        'Forearm slightly tilted',
        'Keep position steady',
        'Natural arm angle',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'g8',
      name: 'Evening',
      category: 'Greetings',
      description: 'Time of day - evening',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/greetings/0021.mp4',
      instructions: [
        'Arm going down like sunset',
        'Palm down',
        'Descending motion',
      ],
      tips: [
        'Think of the sun setting',
        'Smooth downward motion',
        'End at lower position',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase2',
      name: 'Day',
      category: 'Common Phrases',
      description: 'Full day or daytime',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/common_phrases/0022.mp4',
      instructions: [
        'Point to the sky',
        'Arc motion across',
        'Represents sun\'s path',
      ],
      tips: [
        'Full sweeping motion',
        'From one side to other',
        'Keep movement smooth',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase3',
      name: 'Good',
      category: 'Common Phrases',
      description: 'Positive affirmation',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/common_phrases/0023.mp4',
      instructions: [
        'Touch chin with flat hand',
        'Move forward and down',
        'Palm facing up at end',
      ],
      tips: [
        'Start at chin level',
        'Smooth forward motion',
        'Show positive expression',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase4',
      name: 'Bad',
      category: 'Common Phrases',
      description: 'Negative affirmation',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/common_phrases/0024.mp4',
      instructions: [
        'Similar to good but different direction',
        'Touch chin then flip away',
        'Palm ends facing down',
      ],
      tips: [
        'Quick flipping motion',
        'Clear contrast to "good"',
        'Match facial expression',
      ],
      estimatedMinutes: 2,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase5',
      name: 'And',
      category: 'Common Phrases',
      description: 'Connector word for joining ideas',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/common_phrases/0066.mp4',
      instructions: [
        'Make the sign for and',
        'Keep movement compact and clear',
        'Use naturally between signs',
      ],
      tips: [
        'Keep transitions smooth',
        'Avoid exaggerated movement',
        'Maintain consistent rhythm',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
    const GestureModel(
      id: 'phrase6',
      name: 'Can',
      category: 'Common Phrases',
      description: 'Express ability or possibility',
      difficulty: 'Easy',
      videoUrl: 'assets/videos/common_phrases/can.mp4',
      instructions: [
        'Form both hands for the can sign',
        'Bring the hands into position',
        'Show a clear, controlled motion',
      ],
      tips: [
        'Keep handshape consistent',
        'Practice at a natural pace',
        'Pair with facial expression for context',
      ],
      estimatedMinutes: 1,
      isLearned: false,
    ),
  ];

  static final List<Lesson> _lessons = [
    const Lesson(
      id: 'l1',
      title: 'Greetings',
      description: 'Learn common greeting signs',
      icon: '👋',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 8,
      learnedSigns: 2,
      gestureIds: ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g7', 'g8'],
    ),
    const Lesson(
      id: 'l2',
      title: 'Family Members',
      description: 'Signs for family relationships',
      icon: '👨‍👩‍👧‍👦',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 4,
      learnedSigns: 0,
      gestureIds: ['f1', 'f2', 'f3', 'f4'],
    ),
    const Lesson(
      id: 'l3',
      title: 'Numbers ',
      description: 'Basic number signs',
      icon: '🔢',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 11,
      learnedSigns: 0,
      gestureIds: [
        'n0',
        'n1',
        'n2',
        'n3',
        'n4',
        'n5',
        'n6',
        'n7',
        'n8',
        'n9',
        'n10',
        'n54',
      ],
    ),
    const Lesson(
      id: 'l4',
      title: 'Food',
      description: 'Signs related to food and eating',
      icon: '🍽️',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 1,
      learnedSigns: 0,
      gestureIds: ['food1'],
    ),
    const Lesson(
      id: 'l6',
      title: 'Letters A-Z',
      description: 'Practice basic alphabet handshapes',
      icon: '🔤',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 26,
      learnedSigns: 0,
      gestureIds: [
        'letter1',
        'letter2',
        'letter3',
        'letter4',
        'letter5',
        'letter6',
        'letter7',
        'letter8',
        'letter9',
        'letter10',
        'letter11',
        'letter12',
        'letter13',
        'letter14',
        'letter15',
        'letter16',
        'letter17',
        'letter18',
        'letter19',
        'letter20',
        'letter21',
        'letter22',
        'letter23',
        'letter24',
        'letter25',
        'letter26'
      ],
    ),
    const Lesson(
      id: 'l5',
      title: 'Common Phrases',
      description: 'Frequently used expressions',
      icon: '💬',
      imagePath: 'assets/DP.jpeg',
      totalSigns: 6,
      learnedSigns: 0,
      gestureIds: [
        'phrase1',
        'phrase2',
        'phrase3',
        'phrase4',
        'phrase5',
        'phrase6',
      ],
    ),
  ];

  static List<Lesson> getLessons() => _lessons;

  static List<GestureModel> getGestures() => List<GestureModel>.from(_gestures);

  static List<GestureModel> getGesturesByCategory(String category) =>
      _gestures.where((g) => g.category == category).toList();

  static GestureModel? getGestureById(String id) {
    final matches = _gestures.where((g) => g.id == id).toList();
    if (matches.isEmpty) return null;
    return matches.first;
  }

  static Lesson? getLessonById(String id) {
    final matches = _lessons.where((l) => l.id == id).toList();
    if (matches.isEmpty) return null;
    return matches.first;
  }

  static List<GestureModel> getGesturesForLesson(Lesson lesson) {
    return _gestures.where((g) => lesson.gestureIds.contains(g.id)).toList();
  }

  static List<GestureModel> searchGestures(String query) {
    final q = query.toLowerCase();
    return _gestures.where((g) => g.name.toLowerCase().contains(q)).toList();
  }
}
